#- name: PicSearch
#  image: CNN-Image-Retrieval_with_shadow.png
#  url: http://search.yongyuan.name
#  oneliner: CNN for CBIR
#  role: Project Owner
#  description: >
#    After researching CBIR one year, I determined to develop a image retrieval engine demo just 
#    for interest. The convolutional neural networks in the comuter vision community develop so
#    fast in recent  years and show great performance with various tasks. So in my spare time I
#    dive to read papers of CNN and program. The dataset of PicSearch engine is Caltech256, which 
#    contains 29780 images, and until now it supports query in the dataset only.
#  technologies:
#    - CNN
#    - Python
#    - Image Retrieval

#- name: HABIR
#  image: HABIRH_with_shadow.png
#  url: http://yongyuan.name/habir
#  oneliner: Hashing Baseline for Image Retrieval
#  role: Project Owner
#  description: >
#    I do the image retrieval research in early 2013. My mission is to design
#    efficient hashing algorithm to map the semantic similar images to the similar codes.
#    There are two main advantages using hashing method for image retrieval, i.e. storage and
#    computation efficience. To let more researchers focus on design hashing algorithm, I have 
#    built a hashing baseline, hoping this project can do some help for some researchers.
#  technologies:
#    - Matlab
#    - Hashing
#    - Image Retrieval

#- name: PCVwithPython
#  image: PCVH_with_shadow.png
#  url: http://yongyuan.name/pcvwithpython
#  oneliner: Programming Computer Vision with Python(Translate to Chinese)
#  role: Main trainslator
#  description: >
#    I'm a big fun of Python. I think Python is one of the most elegant programming language
#    I have known. It's a great power tool which can be used everywhere, such as write scripts,
#    using Django for web developmentand do science computation. When I first meet the book <Programming 
#    Computer Vision with Python>, I was attracted by the book. The content in this book is 
#    quite rich and diverse and I can't bear to share the book to more people. So in my free time, I dived into
#    the book and translate it into Chinese. Morover, I organized and supply the codes.
#  technologies:
#    - Python
#    - Jekyll
#    - Markdown




